package materia;
/**
 *
 * @author JSQLGen
 */
public class MateriaForm extends javax.swing.JDialog {
    private final java.sql.Connection connection;
    private Materia materia;

    /** Construtor do form MateriaForm
     * @param parent Janela mãe
     * @param connection Conexão com o BD
     * @param materia Objeto a ser editado
     */
    public MateriaForm(java.awt.Window parent, java.sql.Connection connection, Materia materia) {
        super(parent);
        this.connection = connection;
        this.materia = materia;
        initComponents();
        obj2form();
        this.setVisible(true);
    }

    /** Exibe caixa de diálogo para preenchimento dos campos
     * @param parent Janela mãe
     * @param connection Conexão com o BD
     * @param materia Objeto a ser editado
     * @return the materia
     */
    public static Materia showInputDialog(java.awt.Window parent, java.sql.Connection connection, Materia materia) {
        return new MateriaForm(parent, connection, materia).materia;
    }

    /** Transfere os dados do objeto para o formulário */
    private void obj2form() {
        tId.setText(materia.getId()==null?"":materia.getId().toString());
        tCodMateria.setText(materia.getCodMateria()==null?"":materia.getCodMateria());
        tNome.setText(materia.getNome()==null?"":materia.getNome());
        tNomeAbrev.setText(materia.getNomeAbrev()==null?"":materia.getNomeAbrev());
        tDescricao.setText(materia.getDescricao());
    }

    /** Transfere os dados do formulário para o objeto */
    private void form2obj() {
        materia.setId(tId.getText());
        materia.setCodMateria(tCodMateria.getText());
        materia.setNome(tNome.getText());
        materia.setNomeAbrev(tNomeAbrev.getText());
        materia.setDescricao(tDescricao.getText());
    }

    /** valida os dados do formulário */
    private String validateForm() {
        String fieldError ="";
        if(tCodMateria.getText().length()<1) fieldError +="CodMateria\n";
        if(tNome.getText().length()<1) fieldError +="Nome\n";
        if(tNomeAbrev.getText().length()<1) fieldError +="NomeAbrev\n";
        if(tDescricao.getText().length()<1) fieldError +="Descricao\n";
        return fieldError;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pData = new javax.swing.JPanel();
        tbData = new javax.swing.JTabbedPane();
        pButtons = new javax.swing.JPanel();
        bOk = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        tId = new javax.swing.JLabel();
        tCodMateria = new javax.swing.JFormattedTextField();
        tNome = new javax.swing.JFormattedTextField();
        tNomeAbrev = new javax.swing.JFormattedTextField();
        pAulas = new materia.materiaaula.MateriaAulaTab(this, connection, materia);
        tDescricao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Materia");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pData.setLayout(new java.awt.GridLayout(5, 0));
        tId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        tId.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        pData.add(tId);
        tCodMateria.setBorder(javax.swing.BorderFactory.createTitledBorder("CodMateria"));
        pData.add(tCodMateria);
        tNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        pData.add(tNome);
        tNomeAbrev.setBorder(javax.swing.BorderFactory.createTitledBorder("NomeAbrev"));
        pData.add(tNomeAbrev);
        tDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Descricao"));
        pData.add(tDescricao);
        getContentPane().add(pData, java.awt.BorderLayout.NORTH);
        tbData.addTab("Aulas", new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_data-table-16.png")), pAulas); // NOI18N
        getContentPane().add(tbData, java.awt.BorderLayout.CENTER);
        pButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        bOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-accept-16.png"))); // NOI18N
        bOk.setMnemonic('O');
        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });
        pButtons.add(bOk);
        bCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-cancel-16.png"))); // NOI18N
        bCancel.setMnemonic('C');
        bCancel.setText("Cancelar");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        pButtons.add(bCancel);
        getContentPane().add(pButtons, java.awt.BorderLayout.SOUTH);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        String fieldError =validateForm();
        if(fieldError.length()==0) {
            form2obj();
            this.setVisible(false);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Verifique os campos seguintes e tente novamente!\n"+fieldError,"Aviso",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        materia = null;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bCancelActionPerformed


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        bCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOk;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pData;
    private javax.swing.JTabbedPane tbData;
    private javax.swing.JLabel tId;
    private javax.swing.JFormattedTextField tCodMateria;
    private javax.swing.JFormattedTextField tNome;
    private javax.swing.JFormattedTextField tNomeAbrev;
    private javax.swing.JPanel pAulas;
    private javax.swing.JFormattedTextField tDescricao;
    // End of variables declaration//GEN-END:variables
}
