package materia.materiaaula;
/**
 *
 * @author JSQLGen
 */
public class MateriaAulaForm extends javax.swing.JDialog {
    private final java.sql.Connection connection;
    private MateriaAula materiaAula;

    /** Construtor do form MateriaAulaForm
     * @param parent Janela mãe
     * @param connection Conexão com o BD
     * @param materiaAula Objeto a ser editado
     */
    public MateriaAulaForm(java.awt.Window parent, java.sql.Connection connection, MateriaAula materiaAula) {
        super(parent);
        this.connection = connection;
        this.materiaAula = materiaAula;
        initComponents();
        obj2form();
        this.setVisible(true);
    }

    /** Exibe caixa de diálogo para preenchimento dos campos
     * @param parent Janela mãe
     * @param connection Conexão com o BD
     * @param materiaAula Objeto a ser editado
     * @return the materiaAula
     */
    public static MateriaAula showInputDialog(java.awt.Window parent, java.sql.Connection connection, MateriaAula materiaAula) {
        return new MateriaAulaForm(parent, connection, materiaAula).materiaAula;
    }

    /** Transfere os dados do objeto para o formulário */
    private void obj2form() {
        tId.setText(materiaAula.getId()==null?"":materiaAula.getId().toString());
        tCodigo.setText(materiaAula.getCodigo()==null?"":materiaAula.getCodigo());
        tCodMateria.setText(materiaAula.getCodMateria());
        tNomeAula.setText(materiaAula.getNomeAula());
        tDescriAula.setText(materiaAula.getDescriAula());
    }

    /** Transfere os dados do formulário para o objeto */
    private void form2obj() {
        materiaAula.setId(tId.getText());
        materiaAula.setCodigo(tCodigo.getText());
        materiaAula.setCodMateria(tCodMateria.getText());
        materiaAula.setNomeAula(tNomeAula.getText());
        materiaAula.setDescriAula(tDescriAula.getText());
    }

    /** valida os dados do formulário */
    private String validateForm() {
        String fieldError ="";
        if(tCodigo.getText().length()<1) fieldError +="Codigo\n";
        if(tCodMateria.getText().length()<1) fieldError +="CodMateria\n";
        if(tNomeAula.getText().length()<1) fieldError +="NomeAula\n";
        if(tDescriAula.getText().length()<1) fieldError +="DescriAula\n";
        return fieldError;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pData = new javax.swing.JPanel();
        tbData = new javax.swing.JTabbedPane();
        pButtons = new javax.swing.JPanel();
        bOk = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        tId = new javax.swing.JLabel();
        tCodigo = new javax.swing.JFormattedTextField();
        tCodMateria = new javax.swing.JFormattedTextField();
        tNomeAula = new javax.swing.JFormattedTextField();
        tDescriAula = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de MateriaAula");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pData.setLayout(new java.awt.GridLayout(5, 0));
        tId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        tId.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        pData.add(tId);
        tCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo"));
        pData.add(tCodigo);
        tCodMateria.setBorder(javax.swing.BorderFactory.createTitledBorder("CodMateria"));
        pData.add(tCodMateria);
        tNomeAula.setBorder(javax.swing.BorderFactory.createTitledBorder("NomeAula"));
        pData.add(tNomeAula);
        tDescriAula.setBorder(javax.swing.BorderFactory.createTitledBorder("DescriAula"));
        pData.add(tDescriAula);
        getContentPane().add(pData, java.awt.BorderLayout.NORTH);
        getContentPane().add(tbData, java.awt.BorderLayout.CENTER);
        pButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        bOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-accept-16.png"))); // NOI18N
        bOk.setMnemonic('O');
        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });
        pButtons.add(bOk);
        bCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-cancel-16.png"))); // NOI18N
        bCancel.setMnemonic('C');
        bCancel.setText("Cancelar");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        pButtons.add(bCancel);
        getContentPane().add(pButtons, java.awt.BorderLayout.SOUTH);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        String fieldError =validateForm();
        if(fieldError.length()==0) {
            form2obj();
            this.setVisible(false);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Verifique os campos seguintes e tente novamente!\n"+fieldError,"Aviso",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        materiaAula = null;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bCancelActionPerformed


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        bCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOk;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pData;
    private javax.swing.JTabbedPane tbData;
    private javax.swing.JLabel tId;
    private javax.swing.JFormattedTextField tCodigo;
    private javax.swing.JFormattedTextField tCodMateria;
    private javax.swing.JFormattedTextField tNomeAula;
    private javax.swing.JFormattedTextField tDescriAula;
    // End of variables declaration//GEN-END:variables
}
