package adverencia;
/**
 *
 * @author JSQLGen
 */
public class AdverenciaForm extends javax.swing.JDialog {
    private final java.sql.Connection connection;
    private Adverencia adverencia;

    /** Construtor do form AdverenciaForm
     * @param parent Janela mãe
     * @param connection Conexão com o BD
     * @param adverencia Objeto a ser editado
     */
    public AdverenciaForm(java.awt.Window parent, java.sql.Connection connection, Adverencia adverencia) {
        super(parent);
        this.connection = connection;
        this.adverencia = adverencia;
        initComponents();
        obj2form();
        this.setVisible(true);
    }

    /** Exibe caixa de diálogo para preenchimento dos campos
     * @param parent Janela mãe
     * @param connection Conexão com o BD
     * @param adverencia Objeto a ser editado
     * @return the adverencia
     */
    public static Adverencia showInputDialog(java.awt.Window parent, java.sql.Connection connection, Adverencia adverencia) {
        return new AdverenciaForm(parent, connection, adverencia).adverencia;
    }

    /** Transfere os dados do objeto para o formulário */
    private void obj2form() {
        tId.setText(adverencia.getId()==null?"":adverencia.getId().toString());
        cAluno.setSelectedItem(adverencia.getAluno().getMatricula());
        cCoord.setSelectedItem(adverencia.getCoord().getMatricula());
        tData.setText(adverencia.getDataF("dd/MM/yyyy"));
        tObservacao.setText(adverencia.getObservacao());
    }

    /** Transfere os dados do formulário para o objeto */
    private void form2obj() {
        adverencia.setId(tId.getText());
        try{
            adverencia.setAluno(alunos.AlunosDAO.loadByMatricula(connection, Integer.parseInt(cAluno.getSelectedItem().toString())));
        } catch(java.sql.SQLException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Falha na leitura do banco de dados!\n"+e.getMessage(),"Aviso",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        try{
            adverencia.setCoord(coordenador.CoordenadorDAO.loadByMatricula(connection, Integer.parseInt(cCoord.getSelectedItem().toString())));
        } catch(java.sql.SQLException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Falha na leitura do banco de dados!\n"+e.getMessage(),"Aviso",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        adverencia.setDataF("dd/MM/yyyy",tData.getText());
        adverencia.setObservacao(tObservacao.getText());
    }

    /** valida os dados do formulário */
    private String validateForm() {
        String fieldError ="";
        if(cAluno.getSelectedItem()==null) fieldError +="Aluno\n";
        if(cCoord.getSelectedItem()==null) fieldError +="Coord\n";
        if(tObservacao.getText().length()<1) fieldError +="Observacao\n";
        return fieldError;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pData = new javax.swing.JPanel();
        tbData = new javax.swing.JTabbedPane();
        pButtons = new javax.swing.JPanel();
        bOk = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        tId = new javax.swing.JLabel();
        cAluno = new javax.swing.JComboBox(alunos.AlunosDAO.loadMatriculaList(connection).toArray());
        cCoord = new javax.swing.JComboBox(coordenador.CoordenadorDAO.loadMatriculaList(connection).toArray());
        tData = new javax.swing.JFormattedTextField();
        tObservacao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Adverencia");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pData.setLayout(new java.awt.GridLayout(5, 0));
        tId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        tId.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        pData.add(tId);
        cAluno.setBorder(javax.swing.BorderFactory.createTitledBorder("Aluno"));
        pData.add(cAluno);
        cCoord.setBorder(javax.swing.BorderFactory.createTitledBorder("Coord"));
        pData.add(cCoord);
        tData.setBorder(javax.swing.BorderFactory.createTitledBorder("Data"));
        try {
            tData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pData.add(tData);
        tObservacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Observacao"));
        pData.add(tObservacao);
        getContentPane().add(pData, java.awt.BorderLayout.NORTH);
        getContentPane().add(tbData, java.awt.BorderLayout.CENTER);
        pButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        bOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-accept-16.png"))); // NOI18N
        bOk.setMnemonic('O');
        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });
        pButtons.add(bOk);
        bCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-cancel-16.png"))); // NOI18N
        bCancel.setMnemonic('C');
        bCancel.setText("Cancelar");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        pButtons.add(bCancel);
        getContentPane().add(pButtons, java.awt.BorderLayout.SOUTH);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        String fieldError =validateForm();
        if(fieldError.length()==0) {
            form2obj();
            this.setVisible(false);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Verifique os campos seguintes e tente novamente!\n"+fieldError,"Aviso",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        adverencia = null;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bCancelActionPerformed


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        bCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOk;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pData;
    private javax.swing.JTabbedPane tbData;
    private javax.swing.JLabel tId;
    private javax.swing.JComboBox cAluno;
    private javax.swing.JComboBox cCoord;
    private javax.swing.JFormattedTextField tData;
    private javax.swing.JFormattedTextField tObservacao;
    // End of variables declaration//GEN-END:variables
}
