package presencaprof;
/**
 *
 * @author JSQLGen
 */
public class PresencaProfForm extends javax.swing.JDialog {
    private final java.sql.Connection connection;
    private PresencaProf presencaProf;

    /** Construtor do form PresencaProfForm
     * @param parent Janela mãe
     * @param connection Conexão com o BD
     * @param presencaProf Objeto a ser editado
     */
    public PresencaProfForm(java.awt.Window parent, java.sql.Connection connection, PresencaProf presencaProf) {
        super(parent);
        this.connection = connection;
        this.presencaProf = presencaProf;
        initComponents();
        obj2form();
        this.setVisible(true);
    }

    /** Exibe caixa de diálogo para preenchimento dos campos
     * @param parent Janela mãe
     * @param connection Conexão com o BD
     * @param presencaProf Objeto a ser editado
     * @return the presencaProf
     */
    public static PresencaProf showInputDialog(java.awt.Window parent, java.sql.Connection connection, PresencaProf presencaProf) {
        return new PresencaProfForm(parent, connection, presencaProf).presencaProf;
    }

    /** Transfere os dados do objeto para o formulário */
    private void obj2form() {
        tId.setText(presencaProf.getId()==null?"":presencaProf.getId().toString());
        cProfessor.setSelectedItem(presencaProf.getProfessor().getMatricula());
        tEntrada.setText(presencaProf.getEntradaF("dd/MM/yyyy"));
        tSaida.setText(presencaProf.getSaidaF("dd/MM/yyyy"));
        tAtraso.setText(""+presencaProf.getAtraso());
        tObservacao.setText(presencaProf.getObservacao());
        cCoordenador.setSelectedItem(presencaProf.getCoordenador().getMatricula());
    }

    /** Transfere os dados do formulário para o objeto */
    private void form2obj() {
        presencaProf.setId(tId.getText());
        try{
            presencaProf.setProfessor(professor.ProfessorDAO.loadByMatricula(connection, Integer.parseInt(cProfessor.getSelectedItem().toString())));
        } catch(java.sql.SQLException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Falha na leitura do banco de dados!\n"+e.getMessage(),"Aviso",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        presencaProf.setEntradaF("dd/MM/yyyy",tEntrada.getText());
        presencaProf.setSaidaF("dd/MM/yyyy",tSaida.getText());
        presencaProf.setAtraso(tAtraso.getText());
        presencaProf.setObservacao(tObservacao.getText());
        try{
            presencaProf.setCoordenador(coordenador.CoordenadorDAO.loadByMatricula(connection, Integer.parseInt(cCoordenador.getSelectedItem().toString())));
        } catch(java.sql.SQLException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Falha na leitura do banco de dados!\n"+e.getMessage(),"Aviso",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /** valida os dados do formulário */
    private String validateForm() {
        String fieldError ="";
        if(cProfessor.getSelectedItem()==null) fieldError +="Professor\n";
        if(Integer.parseInt(tAtraso.getText())<0) fieldError +="Atraso\n";
        if(tObservacao.getText().length()<1) fieldError +="Observacao\n";
        if(cCoordenador.getSelectedItem()==null) fieldError +="Coordenador\n";
        return fieldError;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pData = new javax.swing.JPanel();
        tbData = new javax.swing.JTabbedPane();
        pButtons = new javax.swing.JPanel();
        bOk = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        tId = new javax.swing.JLabel();
        cProfessor = new javax.swing.JComboBox(professor.ProfessorDAO.loadMatriculaList(connection).toArray());
        tEntrada = new javax.swing.JFormattedTextField();
        tSaida = new javax.swing.JFormattedTextField();
        tAtraso = new javax.swing.JFormattedTextField();
        tObservacao = new javax.swing.JFormattedTextField();
        cCoordenador = new javax.swing.JComboBox(coordenador.CoordenadorDAO.loadMatriculaList(connection).toArray());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de PresencaProf");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pData.setLayout(new java.awt.GridLayout(5, 0));
        tId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        tId.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        pData.add(tId);
        cProfessor.setBorder(javax.swing.BorderFactory.createTitledBorder("Professor"));
        pData.add(cProfessor);
        tEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada"));
        try {
            tEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pData.add(tEntrada);
        tSaida.setBorder(javax.swing.BorderFactory.createTitledBorder("Saida"));
        try {
            tSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pData.add(tSaida);
        tAtraso.setBorder(javax.swing.BorderFactory.createTitledBorder("Atraso"));
        tAtraso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tAtraso.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        pData.add(tAtraso);
        tObservacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Observacao"));
        pData.add(tObservacao);
        cCoordenador.setBorder(javax.swing.BorderFactory.createTitledBorder("Coordenador"));
        pData.add(cCoordenador);
        getContentPane().add(pData, java.awt.BorderLayout.NORTH);
        getContentPane().add(tbData, java.awt.BorderLayout.CENTER);
        pButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        bOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-accept-16.png"))); // NOI18N
        bOk.setMnemonic('O');
        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });
        pButtons.add(bOk);
        bCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-cancel-16.png"))); // NOI18N
        bCancel.setMnemonic('C');
        bCancel.setText("Cancelar");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        pButtons.add(bCancel);
        getContentPane().add(pButtons, java.awt.BorderLayout.SOUTH);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        String fieldError =validateForm();
        if(fieldError.length()==0) {
            form2obj();
            this.setVisible(false);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Verifique os campos seguintes e tente novamente!\n"+fieldError,"Aviso",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        presencaProf = null;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bCancelActionPerformed


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        bCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOk;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pData;
    private javax.swing.JTabbedPane tbData;
    private javax.swing.JLabel tId;
    private javax.swing.JComboBox cProfessor;
    private javax.swing.JFormattedTextField tEntrada;
    private javax.swing.JFormattedTextField tSaida;
    private javax.swing.JFormattedTextField tAtraso;
    private javax.swing.JFormattedTextField tObservacao;
    private javax.swing.JComboBox cCoordenador;
    // End of variables declaration//GEN-END:variables
}
